from http import HTTPStatus

OK = HTTPStatus.OK
CREATED = HTTPStatus.CREATED
BAD_REQUEST = HTTPStatus.BAD_REQUEST
NO_CONTENT = HTTPStatus.NO_CONTENT
UNPROCESSABLE_ENTITY = HTTPStatus.UNPROCESSABLE_ENTITY
INTERNAL_SERVER_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR
UNAUTHORIZED = HTTPStatus.UNAUTHORIZED
NOT_FOUND = HTTPStatus.NOT_FOUND
CONFLICT = HTTPStatus.CONFLICT
TOO_MANY_REQUESTS = HTTPStatus.TOO_MANY_REQUESTS
