import pytest

from parametrs.parametrs_set_password import parameter_generation
from settings import CONFLICT, ENDPOINTS

SIGNUP = ENDPOINTS["signup"]
SET_PASSWORD = ENDPOINTS["set_password"]

params = [
    parameter_generation("valid", "valid", "valid", 200),
    parameter_generation("valid", "valid", "empty", 200),
    parameter_generation("valid", "empty", "valid", CONFLICT),
    parameter_generation("invalid", "valid", "valid", CONFLICT),
    parameter_generation("empty", "valid", "valid", CONFLICT),
    parameter_generation("valid", "empty", "invalid", CONFLICT),
    parameter_generation("valid", "empty", "empty", CONFLICT),
    parameter_generation("invalid", "valid", "invalid", CONFLICT),
    parameter_generation("invalid", "valid", "empty", CONFLICT),
    parameter_generation("empty", "valid", "invalid", CONFLICT),
    parameter_generation("empty", "valid", "empty", CONFLICT),
    parameter_generation("invalid", "invalid", "valid", CONFLICT),
    parameter_generation("invalid", "empty", "valid", CONFLICT),
    parameter_generation("empty", "invalid", "valid", CONFLICT),
]

ids = [
    f"password={password},nickname={nickname},timezone={timezone},status={status}"
    for password, nickname, timezone, status in params
]


@pytest.fixture(params=params, ids=ids)
def set_password_params(request):
    """
    Fixture that provides parameterized test data for set password-related tests.

    Args:
        request: Pytest request object containing the parameterized test data.

    Returns:
        tuple: A tuple containing the password, nickname, timezone, and expected status code
               for a set password test case, as generated by `parameter_generation`.

    The fixture uses the `params` list, which contains test cases generated by
    `parameter_generation` from `parametrs_set_password`. Each test case includes:
        - password (str): The password parameter (e.g., valid, invalid, empty).
        - nickname (str): The nickname parameter (e.g., valid, invalid, empty).
        - timezone (str): The timezone parameter (e.g., valid, invalid, empty).
        - status (int): The expected HTTP status code for the test case (e.g., 200, 400).

    The `ids` list provides descriptive identifiers for each test case in the format:
    'password={password},nickname={nickname},timezone={timezone},status={status}' for better test reporting.
    """
    return request.param
