import pytest

from parametrs.parameters_signup import parameter_generation
from settings import CONFLICT, ENDPOINTS, INTERNAL_SERVER_ERROR, OK, TOO_MANY_REQUESTS

SIGNUP = ENDPOINTS["signup"]


params = [
    parameter_generation("invalid", "valid", CONFLICT),
    parameter_generation("valid", "valid", OK),
    parameter_generation("valid", "empty", OK),
    parameter_generation("empty", "valid", CONFLICT),
    parameter_generation("long", "valid", INTERNAL_SERVER_ERROR),
    parameter_generation("malformed", "valid", CONFLICT),
    parameter_generation("valid", "invalid", CONFLICT),
    parameter_generation("valid", "null", OK),
    parameter_generation("valid", "long", CONFLICT),
    parameter_generation("xss", "valid", CONFLICT),
    parameter_generation("valid", "xss", CONFLICT),
]

ids = [f"email={email},lang={lang},status={status}" for email, lang, status in params]


@pytest.fixture(params=params, ids=ids)
def signup_params(request):
    """
    Fixture that provides parameterized test data for signup-related tests.

    Args:
        request: Pytest request object containing the parameterized test data.

    Returns:
        tuple: A tuple containing the email, language, and expected status code
               for a signup test case, as generated by `parameter_generation`.

    The fixture uses the `params` list, which contains test cases generated by
    `parameter_generation` from `parameters_signup`. Each test case includes:
        - email (str): The email parameter (e.g., valid, invalid, empty, long, malformed, xss).
        - lang (str): The language parameter (e.g., valid, empty, invalid, null, long, xss).
        - status (int): The expected HTTP status code for the test case (e.g., 200, 400, 500).

    The `ids` list provides descriptive identifiers for each test case in the format:
    'email={email},lang={lang},status={status}' for better test reporting.
    """
    return request.param
