import pytest

from parametrs.parameters_signup import parameter_generation as signup_params
from parametrs.parametrs_set_password import parameter_generation as set_password_params
from settings import ENDPOINTS
from utils.fake_data_generators import generate_password

OK = 200
SIGNUP = ENDPOINTS["signup"]
SET_PASSWORD = ENDPOINTS["set_password"]
RESET_PASSWORD = ENDPOINTS["reset_password"]
FORGOT_PASS = ENDPOINTS["forgot_password"]

params = [
    {
        "signup": signup_params("valid", "valid", OK),
        "set_pass": set_password_params("valid", "valid", "valid", OK, token=True),
        "forgot_pass": {"email": ""},
        "reset_pass": {
            "token": "",
            "newPassword": generate_password(),
            "timezone": "UTC+7",
        },
    },
]

ids = [
    f"signup={signup},set_pass={set_pass},forgot_pass={forgot_pass},reset_pass={reset_pass}"
    for signup, set_pass, forgot_pass, reset_pass in params
]


@pytest.fixture(params=params, ids=ids)
def reset_password_params(request):
    """
    Fixture that provides parameterized test data for reset password-related tests.

    Args:
        request: Pytest request object containing the parameterized test data.

    Returns:
        tuple: A tuple containing the password, nickname, timezone, and expected status code
               for a reset password test case, as generated by `parameter_generation`.

    The fixture uses the `params` list, which contains test cases generated by
    `parameter_generation` from `parametrs_set_password`. Each test case includes:
        - password (str): The password parameter (e.g., valid, invalid, empty).
        - nickname (str): The nickname parameter (e.g., valid).
        - timezone (str): The timezone parameter (e.g., valid, invalid, empty).
        - status (int): The expected HTTP status code for the test case (e.g., 200, 400).

    The `ids` list provides descriptive identifiers for each test case in the format:
    'password={password},nickname={nickname},timezone={timezone},status={status}' for better test reporting.

    Note:
        The fixture currently includes only one active test case (all valid parameters).
        Additional test cases are commented out but can be enabled to test various invalid
        or empty parameter combinations, each expecting a 400 status code.
    """
    return request.param
