import pytest

from settings import ENDPOINTS
from utils.fake_data_generators import (
    generate_email,
    generate_nickname,
    generate_password,
)

OK = 200
SIGNUP = ENDPOINTS["signup"]
SET_PASSWORD = ENDPOINTS["set_password"]
FORGOT_PASSWORD = ENDPOINTS["forgot_password"]

params = [
    {
        "signup": {"email": generate_email(), "lang": "en"},
        "set_password": {
            "newPassword": generate_password(),
            "nickname": generate_nickname(),
            "timezone": "",
        },
        "forgot_password": {"email": None},
    },
    {
        "signup": {"email": generate_email(), "lang": "ru"},
        "set_password": {
            "newPassword": generate_password(),
            "nickname": generate_nickname(),
            "timezone": "UTC",
        },
        "forgot_password": {"email": None},
    },
]

ids = ["valid_en", "valid_ru"]


@pytest.fixture(params=params, ids=ids)
def forgot_password_data(request):
    """
    Fixture that provides parameterized test data for forgot password-related tests.

    Args:
        request: Pytest request object containing the parameterized test data.

    Returns:
        dict: A dictionary containing test data for signup, set password, and forgot password
              endpoints, as defined in the `params` list.

    The fixture uses the `params` list, which contains test cases with the following structure:
        - signup (dict): Contains 'email' (generated by `generate_email`) and 'lang' (language code, e.g., 'en' or 'ru').
        - set_password (dict): Contains 'newPassword' (generated by `generate_password`),
                              'nickname' (generated by `generate_nickname`), and 'timezone' (e.g., empty or 'UTC').
        - forgot_password (dict): Contains 'email' (currently set to None).

    The `ids` list provides descriptive identifiers for each test case ('valid_en', 'valid_ru')
    for better test reporting.
    """
    return request.param
