import pytest

from settings import ENDPOINTS
from utils.fake_data_generators import (
    generate_email,
    generate_nickname,
    generate_password,
)

OK = 200
SIGNUP = ENDPOINTS["signup"]
SET_PASSWORD = ENDPOINTS["set_password"]
CHANGE_PASSWORD = ENDPOINTS["change_password"]

@pytest.fixture(params=["en", "ru"], ids=["valid_en", "valid_ru"])
def change_password_data(request):
    """
    Fixture that provides parameterized test data for change password-related tests.
    
    Args:
        request: Pytest request object containing the language parameter ('en' or 'ru').
    
    Returns:
        dict: A dictionary containing test data for signup, set password, and change password
              endpoints, with configurations that vary based on the language parameter.
    
    The fixture parameterizes over two language options:
        - 'en' (English): Uses empty timezone in set_password data
        - 'ru' (Russian): Uses 'UTC' timezone in set_password data
    
    The returned dictionary includes:
        - signup (dict): Contains 'email' (generated by `generate_email`) and 'lang' (from parameter)
        - set_password (dict): Contains 'newPassword' (generated by `generate_password`),
                              'nickname' (generated by `generate_nickname`), and 'timezone'
                              (set to 'UTC' for Russian, empty for English)
        - change_password (dict): Contains 'oldPassword' (currently set to None) and 
                                 'newPassword' (generated by `generate_password`)
    
    The `ids` parameter provides descriptive identifiers for each test case 
    ('valid_en', 'valid_ru') for better test reporting.
    """
    lang = request.param
    return {
        "signup": {"email": generate_email(), "lang": lang},
        "set_password": {
            "newPassword": generate_password(),
            "nickname": generate_nickname(),
            "timezone": "UTC" if lang == "ru" else "",
        },
        "change_password": {
            "oldPassword": None,
            "newPassword": generate_password(),
        },
    }